apiVersion: v1
kind: Pod
metadata:
  name: hello
spec:
  containers:
  - name: busybox-container
    image: busybox:latest
    command:
    - sh
    - -c
    - while true; do echo New random number is $(( ( RANDOM % 100 ) + 1 )); sleep 2; done
