services:
  gen:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      APP_DEBUG: "false"
      TO_USERNAME: "rmuser"
      TO_PASSWORD: "rmpassword"
      TO_HOSTNAME: "rabbitmq"
      TO_PORT: "5672"
      TO_QUEUE: "inbox"
      TO_EXCHANGE: "in"
      TO_ROUTINGKEY: "gen"
      TO_PASSIVE: "false"
      MCH_MODE: "false"
      JOB_MODE: "false"
      COUNT: "1000000"
      SLEEP: "100"

